### ISSUE TITLE
Evaluate CopyWebPackPlugin to manage large assets

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/geppetto-meta#102]
For the showcase examples, we use `import` statements to load large JSON files and webpack converts these files to JS files during build time.

However, this approach doesn't work for other binary resources types and could be potentially responsible for the high memory consumption of webpack.

We can use the `CopyWebPackPlugin` to copy these files to the assets folder and use `fetch` to have more flexibility and control over the loading time.

https://stackoverflow.com/a/58889499/8276960

**Comment by lrebscher** [comment]
Related to #18

**Comment by enicolasgomez** [comment]
This is how the bundle *looked* like before the optimization:

![image](https://user-images.githubusercontent.com/5366927/133312208-3e16770a-11fe-4c6f-9b87-e7d4bdca21b8.png)

This is how the bundle looks like after:

![bundle](https://user-images.githubusercontent.com/5366927/133311766-f15847d0-5599-4606-b17f-7295b019e245.png)

This was the memory consuptio *before* the optimization:

![image](https://user-images.githubusercontent.com/5366927/133312349-b0429cce-0952-46f1-8511-d009f77e2fb7.png)

**Comment by enicolasgomez** [comment]
Unfortunately, the memory consumption equals the one that @afonsobspinto initially reported. Need to keep looking into this.
