### ISSUE TITLE
Improve local dev setup for geppetto-core/ui/client in showcase & example app

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/geppetto-meta#106]
Need setup script for showcase & example app to install yalc package of geppetto-x packages.

script needs to push the change after each run as well.

We already have one for example app, need to write one for showcase & extend README in both projects

**Comment by afonsobspinto** [comment]
Showcase can't use the build folder/package of geppetto-ui. It requires both the json files and the non-minified versions of the javascript files.
(This is the cause of the problem you had @ddelpiano )

**Comment by afonsobspinto** [comment]
geppetto-showcase can't use `yarn build` but rather `yarn build:src` (because it needs the .json and the non-minified version of the .js files).
Leaving this here because the example script uses the first command and was the origin of some problems for @ddelpiano
