### ISSUE TITLE
Complete refactoring of geppetto-core

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/geppetto-meta#115]
* [ ] GEPPETTO.Manager dependency to Model must be removed, resolveImportValue, fetchVariables, resolveImportType
* [ ] Remove GEPPETTO.CommandController, replace `exceute`calls by using code expression directly without passing it to controller
* [ ] Refactor use of GEPPETTO.Utility -> we already have Utility.js in geppetto-core, just have to use it instead of GEPPETTO.Utility
* [ ] Remove GEPPETTO.MessageSocket used in ProjectNode
* [ ] Remove  GEPPETTO.SceneController, it's used but it was already removed!
* [ ] Remove VisualCapability.js & AVisualGroupCapability.js
* [ ] EventManager must be refactored. Internal of geppetto-model shouldn’t know about EventManager and store, it’s too strongly coupled
* [ ] Move related events/actions to geppetto-core, currently EventManager contains all actions
* [ ] Remove dependency of model to a Project & maybe even remove ProjectFactory itself?
* [ ] Use import to access GEPPETTO.Resources, Resources.js is already part of geppetto-core, just have to change the usage. Two steps:  (1) search+replace all occurrences (2) add import statements to related files

**Comment by afonsobspinto** [comment]
What's your take on the state of this issue after #175  @filippomc ?

**Comment by filippomc** [comment]
this was done with #175, yes.
