### ISSUE TITLE
Add widget to example app that uses config as prop in component

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/geppetto-meta#129]

**Comment by afonsobspinto** [comment]
This is how I'm doing it in neuroscan:
https://github.com/MetaCell/geppetto-NeuroSCAN/blob/feature/22/frontend/src/redux/middleware.js#L23
https://github.com/MetaCell/geppetto-NeuroSCAN/blob/feature/22/frontend/src/components/viewers/MorphologyViewer.jsx#L7
