### ISSUE TITLE
Populate Canvas in Example app with data

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/geppetto-meta#136]
Similar to SimpleInstanceExample in showcase we can create some example data. 

The difference here should be that we don't import the obj/gltf file by using webpack supported `import` statement, but rather store the files either in the public folder or a common storage that also the geppetto-showcase is using to fetch data (e.g. Google cloud storage).

**Comment by enicolasgomez** [comment]
@Muhaddatha you can follow this geppetto-showcase approach:

https://github.com/MetaCell/geppetto-meta/blob/development/geppetto.js/geppetto-ui/src/3d-canvas/showcase/examples/AuditoryCortexExample2.js#L113
