### ISSUE TITLE
Move camera with arrow keys across scene

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/geppetto-meta#144]
Atm we can use the mouse to rotate and zoom, we can also pan by holding right mouse key and moving mouse.

The Canvas showcase should be extended to show how to wire the arrow keys to cameraManager actions in order to move the camera with these keys.

We currently use [TrackballControls](https://threejs.org/docs/#examples/en/controls/TrackballControls)

[OrbitControls has an object that references keycodes for arrow keys](https://threejs.org/docs/#examples/en/controls/OrbitControls.keys)

Need to evaluate if we can achieve the same with TrackballControls or even use both at the same time?

Threejs offers a [variety](https://threejs.org/docs/?q=Controls#examples/en/controls/FlyControls) of different controls

**Comment by lrebscher** [comment]
Also see previous Canvas controls in [geppetto-client repository](https://github.com/openworm/geppetto-client/blob/master/js/components/interface/3dCanvas/TrackballControls.js)

**Comment by afonsobspinto** [comment]
If it is simple to add, like just add an event-listener to the arrow keys that trigger the appropriate methods, I guess it won't cause any harm. 
But if we need to replace trackball controls with other xControls I wouldn't do it unless necessary (requested by some application ).
What's your take on this @enicolasgomez ?

**Comment by ddelpiano** [comment]
note for myself, check the above with Afonso

**Comment by enicolasgomez** [comment]
Since we moved to an  "on demand rendering" this won't be trivial to implement, I see this similar to the camera spin button in which requestRenderFrame will be triggered by a setTimeOut call with the extra complecity of the rotation angle. I don't think it worth the effort right now.
