### ISSUE TITLE
Include sourceMap in transpiled packages

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/geppetto-meta#145]
The geppetto.js packages are transpiled to commonjs, but without adding sourceMap information.

For debugging it would be handy to add the sourceMap information.

Could be as easy as configuring the [sourceMaps attribute in babel](https://babeljs.io/docs/en/options#sourcemaps)

**Comment by enicolasgomez** [comment]
Unfortunately just adding sourceMaps to Babel didn't do the trick. Looking in deep.

**Comment by enicolasgomez** [comment]
This was checked to be working for showcase but not for react sample app. Closing by now.
