### ISSUE TITLE
Check 100% CPU usage IN YALE

### ISSUE THREAD

**Issue by enicolasgomez** [MetaCell/geppetto-meta#146]

**Comment by zsinnema** [comment]
also in Yale: https://yale.metacell.us/
click 'add element' and then click 'Add Cphate Viewer'
cpu will go up to >300%

**Comment by enicolasgomez** [comment]
Please see:
https://github.com/MetaCell/open-physiology-viewer/issues/31

Same solution has been implemented and now the CPU usage has been dramatically reduced.

On a side note, OrtbitControl and TrackBallControll now co-exist. We'll need to discuss if we want to merge functionality for these two components.

**Comment by enicolasgomez** [comment]
Closing  as duplicates #150

**Comment by zsinnema** [comment]
imo it's not a duplicate but a new issue
although I'm also not sure if we can do something about it
the converting of the obj's (>1500)  to the webgl scene is the issue

**Comment by enicolasgomez** [comment]
@zsinnema  Ok, i got your point, let me try this in Yale and see how it goes. Let's change the subject.

**Comment by enicolasgomez** [comment]
putting together @zsinnema reports

https://user-images.githubusercontent.com/5366927/133274756-143ef4a6-4852-4c55-b13a-0ac6b630cd71.mp4


https://user-images.githubusercontent.com/5366927/133274760-f900088c-45f5-4906-b46d-65f11ef4cc00.mp4

**Comment by enicolasgomez** [comment]
putting together @zsinnema 's report 


https://user-images.githubusercontent.com/5366927/133276121-b7c59b8f-4080-4646-839e-97c9a1acbfd4.mp4


https://user-images.githubusercontent.com/5366927/133276136-f1ff1d5c-9e18-49e1-82c0-242aa6ae3555.mp4
