### ISSUE TITLE
High Prio: switching between tabs in flexlayout recreates all the obj meshes

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/geppetto-meta#149]
In a flexlayout with multiple tabs with canvases switching between the tabs triggers a "Resize" event causing all obj files on a canvas (f.e. SimpleInstances)  to be "recalculated". When having a lot of Simpleinstances on the canvas this leads to high performance loss. E.g. in Yale switching between 2 Cphate viewers on a flexlayout takes >10 seconds.

**Comment by filippomc** [comment]
See also #135

**Comment by ddelpiano** [comment]
this has been addressed by the resizing component and also by the refactoring done recently where we are not flushing the scene anymore if the instances list did not change - @enicolasgomez can we close this? thx
