### ISSUE TITLE
3DCanvas: position set to point zero and frozen when not set when reset false

### ISSUE THREAD

**Issue by filippomc** [MetaCell/geppetto-meta#158]
When cameraOptions position and rotation are not set from the prop, it should be automatically adjusted by threejs to fit with the content.

What's happening instead is that the first call to the cameraHandler set the position to zero and the rotation has some invalid value.
If we use the rotation value, the camera freezes and cannot be moved.
This may be a transitory problem, but after that set the camera freezes.

**Comment by afonsobspinto** [comment]
Also, consider 'use the props only on mount, ignore otherwise (shouldComponentUpdate logic)'

**Comment by filippomc** [comment]
To replicate: https://github.com/MetaCell/geppetto-meta/blob/master/geppetto.js/geppetto-ui/src/3d-canvas/showcase/examples/CA1CellExample.js and remove the initial camera position and rotation from the state

**Comment by afonsobspinto** [comment]
Imo can be closed. cc @enicolasgomez
