### ISSUE TITLE
Layout tab title changes back to "initial" title after update widget

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/geppetto-meta#161]
After an update widget the title of the tab is changed to the initial title

see video
[layout_title_change_after_widget_update.webm.zip](https://github.com/MetaCell/geppetto-meta/files/7183882/layout_title_change_after_widget_update.webm.zip)

**Comment by filippomc** [comment]
this is related to the fact that the middleware in the layout manager is not detecting the tab name change, like it is doing, for instance, on tab selections.
Need to catch the Actions.RENAME_TAB[ in the onAction switchcase](https://github.com/MetaCell/geppetto-meta/blob/development/geppetto.js/geppetto-client/js/common/layout/LayoutManager.tsx#L359 ) and dispatch an updateWidget action with the new name

**Comment by zsinnema** [comment]
@filippomc imo the internal model of the layout manager should be updated instead of sending an updateWidget action
the widget update was already done (in a step before)

**Comment by filippomc** [comment]
The update is needed as the widget configuration in the redux state is the source of truth: if we don't update it, we will get the model reset to the old value with the next action.
The layoutmanager is actually mapping to our redux state the internal state of the flexlayout component in order to make the configuration process simple and repeatable. Keeping them aligned is essential.

**Comment by zsinnema** [comment]
I mean when you do a rename of the tab then a SET_LAYOUT is dispatched with the name change
the bug is that the internal model isn't updated

**Comment by zsinnema** [comment]
btw imo the name of the tab should not be equal to the name of the widget

the widget is a child of the tab element so there can me multiple widgets on a tab

**Comment by filippomc** [comment]
the internal layout model depends on the widget configuration. We don't manipulate directly the layout, the layout is a subproduct of the widget configuration as required by the flexlayout library

**Comment by filippomc** [comment]
> btw imo the name of the tab should not be equal to the name of the widget
there is only one widget per tab. Everything that is related to that tab should be configurable with an UPDATE_WIDGET action

**Comment by zsinnema** [comment]
yes correct it should have been:

> btw imo the name of the tab should not be equal to the name of the widget the widget is a property of the tab element

**Comment by filippomc** [comment]
the widget is a higher level specification of the layout. The layout (and the tab inside) are a subproduct of the widget configuration. The reason why the layout is part of the redux state is a shortcut to persist fine grained manipulations of the layout through the ui, but whenever something is supported by a widget, the widget should take precedence

**Comment by zsinnema** [comment]
imo this is a flaw in the design, we should never store the same data in 2 different places, this introduces this kind of bugs
I propose to remove the widgets completely since they are part of the layout and use layout in the way we use widgets

**Comment by filippomc** [comment]
The layout is not our api, it's flexlayout library api, and it's too complex and messy to our needs. We just want a list of configurable widgets mapped to components that say high level what they are and what they want to be. 
Agree that the double information is not ideal, but the layout is in the store only for save/reload, and may be removed by implementing a save/reload mechanism for the layout that does not pass through redux.

**Comment by ddelpiano** [comment]
#168 looks good to me, @zsinnema I am re-assigning this to you to close the issue whenever you get a chance to test the latest, if you are ok with that. Thx
