### ISSUE TITLE
README formatting ignored and more annoyingly printed out

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-meta#17]
as per image, this is what I get from the search component readme that has a quite long description and code snippet.

![Screenshot 2020-09-28 at 10 43 27](https://user-images.githubusercontent.com/37704177/94454123-63c6b600-01a9-11eb-81a0-536541d38d28.png)

**Comment by afonsobspinto** [comment]
Also fix:
![image](https://user-images.githubusercontent.com/19196034/112625480-e235a500-8e26-11eb-96fc-c464e64dcd8d.png)

**Comment by afonsobspinto** [comment]
The original problem is not a bug but an enhancement. 
Showcase doesn't work with any readme but rather the ones that follow the [Geppetto showcase template](https://github.com/MetaCell/lunapark-dev/wiki/Geppetto-Showcase-Template).

The [search readme](https://github.com/openworm/geppetto-client/blob/development/geppetto-ui/src/search/README.md) doesn't follow the template schema and the content of the readme seems to somehow overlap the features provided by the showcase:

- Component dependencies overlap with Libraries on the template schema
- How to use the component -> Props overlaps with the automatic generation of props table from Proptypes ([point 2](https://github.com/MetaCell/lunapark-dev/wiki/Geppetto-Showcase-Development))
- Code snippets of the usage/instantiation are automatically found and displayed as well.

In this context, I renamed the original readme file to README_detailed.md and created a new one, as a placeholder, that follows the template:

![image](https://user-images.githubusercontent.com/19196034/112661211-2ee0a680-8e4e-11eb-9ac1-6adb9d3b0f7a.png)

I also created issue https://github.com/MetaCell/geppetto-meta/issues/36 based on this.
Issues #1 and #2 are also relevant. For now added workarounds for Search component placeholder as well
