### ISSUE TITLE
Evaluate webpack memory consumption 

### ISSUE THREAD

**Issue by afonsobspinto** [MetaCell/geppetto-meta#18]
Image below shows webpack memory consumption for geppetto-website and ifn respectively. The goal of this issue is to try to understand if the disparity between memory usage is reasonable or if there's something we can improve on geppetto-website
![image](https://user-images.githubusercontent.com/19196034/108056329-042e5180-7049-11eb-9a62-8728b7a133d4.png)

**Comment by enicolasgomez** [comment]
Please refer here:
https://app.zenhub.com/workspaces/geppetto-meta-6047b13d88e7e70013d4589b/issues/metacell/geppetto-meta/102
