### ISSUE TITLE
Don't force GEPPETTO_CONFIGURATION variable definition

### ISSUE THREAD

**Issue by afonsobspinto** [MetaCell/geppetto-meta#188]
I was having the following error on geppetto-Neuroscan after changing to the latest geppetto-meta (version 1.0.0-alpha1 : containing #175)
![image](https://user-images.githubusercontent.com/19196034/138757761-aaf3dc2b-a262-4dab-8231-b77bfd4c2a0f.png)

This is coming from: https://github.com/MetaCell/geppetto-meta/blob/feature/175/geppetto.js/geppetto-client/src/communication/MessageSocket.js#L30

I don't think geppetto-Neuroscan uses the MessageSocket (it just mocks the Geppetto object in the frontend) so it doesn't seem right that I have to define GEPPETTO_CONFIGURATION to be able to use geppetto-meta-client.

`        new webpack.DefinePlugin({
          GEPPETTO_CONFIGURATION: {},
        }),`

**Comment by afonsobspinto** [comment]
Might be fixed by #220

**Comment by enicolasgomez** [comment]
@afonsobspinto please check if it's been fixed as you mentioned above
