### ISSUE TITLE
Fix incorrect action (zoom, camera movement) propagation Canvas

### ISSUE THREAD

**Issue by afonsobspinto** [MetaCell/geppetto-meta#196]
Since #195 got merged. I'm opening this PR to track the following issues:

https://github.com/MetaCell/geppetto-meta/pull/195#issuecomment-957306890

**Comment by afonsobspinto** [comment]
On geppetto-meeting:
>Is it a problem with the examples?

No. It seems to be happening in Yale as well

https://user-images.githubusercontent.com/19196034/140562253-0397880f-542b-48db-9f15-7a9642f89a46.mp4

**Comment by ddelpiano** [comment]
raising this since it happens also in netpyne

**Comment by afonsobspinto** [comment]
I don't think this is related with #321 because I still see this bug with the trackball controls from threejs (without our changes) but not #321
