### ISSUE TITLE
Scene shows no instances after resizing

### ISSUE THREAD

**Issue by zsinnema** [MetaCell/geppetto-meta#198]
After resizing the instances are not showing anymore on the canvas.
See video
I put a breakpoint on the function where the canvas is rendered. As you can see this function is NOT being called when the resize takes place. This is a very nice improvement! 
However the instances are removed from the scene

https://user-images.githubusercontent.com/124044/139847216-79f1b151-0f49-4e41-ab77-109613d13505.mp4

**Comment by filippomc** [comment]
May be related to #178?

**Comment by zsinnema** [comment]
@filippomc no it is not related, I've debugged it and there is no rerender of the canvas and therefore imo not related to #178 . As said during todays call when I change the color of the instance it will be redrawn on the scene --> instances on the config of the widget are good
