### ISSUE TITLE
Refactor geppetto-client into Geppetto.js

### ISSUE THREAD

**Issue by tarelli** [MetaCell/geppetto-meta#21]

**Comment by lrebscher** [comment]
**High-level overview**

* No need for a project to be required (remove project completely?)
* Remove embedded user management
* Decouple model creation 
* Avoid global variables
* Remove Javascript console
* Separate control logic from model logic

**Comment by lrebscher** [comment]
**High-level overview**

* The goal is to offer a modular and flexible framework
* No need for a project to be required (remove project completely?)
* Remove embedded user management (*GEPPETTO.UserController.js*)
* Remove obsolete methods from Websocket API  (#29)
* Remove pages (*geppetto-client/js/pages*)
* Decouple model creation 
* Avoid global variables
* Remove Javascript console
* Separate control logic from model logic
* Replacement of Backbone js with Redux (Ongoing: https://github.com/openworm/geppetto-client/pull/282 )

**Further notes:**

* Reduce indirections in Geppetto model
* Don't assume that we have a stateful backend
