### ISSUE TITLE
getIntersectedObjects() sometimes fails to pull the actual objects

### ISSUE THREAD

**Issue by enicolasgomez** [MetaCell/geppetto-meta#223]
Seems like there's something wrong with how mouse coordinates are calculated and passed to the raytracer, because sometimes it returns false positives and other times false negatives.

**Comment by enicolasgomez** [comment]
@Muhaddatha please merge from relaese/v1.0.0-rc1 while working on this one

**Comment by enicolasgomez** [comment]
This could be of help:

https://stackoverflow.com/questions/24035234/three-js-raycast-off-from-mouse-position

**Comment by enicolasgomez** [comment]
A working sample:

https://jsfiddle.net/5z13yzgx/

**Comment by Muhaddatha** [comment]
View from virtual machine (Linux) running on a Windows host computer. File was too big to upload on ZenHub, so I linked it here:
https://drive.google.com/file/d/1RD3hZaNdAg_o7B_8lLjmipLuBcExQdbB/view?usp=sharing

**Comment by enicolasgomez** [comment]
This has been put on hold as it only affects MacOS

**Comment by enicolasgomez** [comment]
This is why it's failing for MacOS only:

https://stackoverflow.com/questions/28821669/three-js-javascript-raycasting-code-not-compatible-with-retina-display-macs
