### ISSUE TITLE
gltf material/color got lost after one re-render

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-meta#236]
gltf are loaded initially with a native color contained in the gltf itself, since the material file is merged with them.
However after the first rendering the color is lost and reset to default.

In the video you can see that the gltf files are rendered gray first (original color) but then they switch to the blue default color of geppetto.

**Comment by ddelpiano** [comment]
https://user-images.githubusercontent.com/37704177/145392808-c9b012ee-65b2-4a3d-a8b5-9cd7e7a2838e.mp4

**Comment by enicolasgomez** [comment]
@ddelpiano @zsinnema after going over this with Zoran we were not able to reproduce it nor in my local version or in his
