### ISSUE TITLE
refactor geppeto-js showcase components to use CopyPlugin for large sample files

### ISSUE THREAD

**Issue by enicolasgomez** [MetaCell/geppetto-meta#305]
In this commit:

https://github.com/MetaCell/geppetto-meta/commit/c7393d9aadfe871ef0ec7380a8fd4696c27322ba

instances-small.json and model.json have been converted to JS so it can be included directly in the components. e.g.
geppetto.js/geppetto-ui/src/menu/showcase/examples/MenuShowcase.js

The problem with having these large files is that they are bundled into the app making it really heavy. For this same scenario in other files, the show case is using CopyPlugin.

Things to do here:

- Investigate if we can refactor the geppetto-js components into the showcase, as they seem to be only used there.
- Once refactored, use CopyPlugin to follow the same stategy with previous large sample files

**Comment by Muhaddatha** [comment]
@enicolasgomez I looked into this and here is what I found. Showcase examples are coming from component markdown. That means their name and description are parsed from a markdown for that particular component.

**Comment by Muhaddatha** [comment]
As far as refactoring,

**Comment by Muhaddatha** [comment]
As far as refactoring,
everything is refactored except VR canvas in the showcase. I wasn't able to refactor this one. Right now, it's being used from inside the [geppetto-ui folder](https://github.com/MetaCell/geppetto-meta/tree/development/geppetto.js/geppetto-ui).

A few things I noticed are:
- Graph visualization nodes are much larger than before. I'm not sure why this is happening because I haven't changed any code other than import statements.
- Some Canvas components lost color (VFB lost background color, simple and multiple instances have a single color instead of two). Not sure what's causing this either (same reason as above).

If we want to continue with this implementation, I can move on to using CopyPlugin. Let me know what you think @enicolasgomez 
cc @afonsobspinto 

Note: Please ignore the `showcase` folders still left in geppetto-ui folder. I will remove them soon if this approach is approved.

[commits](https://github.com/MetaCell/geppetto-meta/commits/feature/305_refactor_showcase_examples)

**Comment by afonsobspinto** [comment]
I believe that originally we wanted to keep the showcase folders close to the components to somehow facilitate it's developing,
but this was coming from a time that we didn't have a mono-repo so regarding that point I think it's fine that we move them to the geppetto-showcase folder if there are no complications. 

I have a question tho. What are we doing with the README.md on each UI components? They served the purpose of sort of documentate the component and guide the geppetto-showcase app to connect the examples.
If we are not moving it, we need some sort of replacement, which I guess is what the ShowcaseExamplesComponentsMap is all about. I would rather have the readme.md but I might be biased :stuck_out_tongue: 

Let's bring this up in the next geppetto meeting. I honestly think we might not need such a change and we just have 2 different builds. One for geppetto-ui package publish that doesn't include showcase folder and one for geppetto-showcase that does.

Good call on putting this on hold until further notice @Muhaddatha 

Regarding your issues:
There should be no reference from our UI components to the showcase folders. Could you please link the code section that is doing that in the VR Canvas? Most likely it's a mistake.

For the other ones I haven't looked into them yet. I can look into when you open the PR if this moves forward, is that ok?

**Comment by Muhaddatha** [comment]
To answer your question about the README files, they're still being used to find the correct component from its name after the file is parsed in [this function](https://github.com/MetaCell/geppetto-meta/blob/a4f6760a5c55899fcacd08707b4b04c9273503ac/geppetto-showcase/src/components/showcase/Showcase.jsx#L100). So, the cases in the [ShowcaseExamplesComponentMap ](https://github.com/MetaCell/geppetto-meta/blob/a4f6760a5c55899fcacd08707b4b04c9273503ac/geppetto-showcase/src/components/examples/ShowcaseExamplesComponentsMap.js#L65) are coming straight from the README. I tried to make minimal changes to preserve the original structure. So  no worries about your README file. It's intact and in use 😉 @afonsobspinto

**Comment by afonsobspinto** [comment]
Good to know that [my precious readme files](https://user-images.githubusercontent.com/19196034/159466711-acac43b5-bbf0-4c4e-b70b-228c9e9adbc0.png) are still in use. But in that case, I don't fully understand why we need the ShowcaseExamplesComponentMap

**Comment by Muhaddatha** [comment]
I have some updates on this card:
- As we have discussed, the showcase is now using [relative paths ](https://github.com/MetaCell/geppetto-meta/blob/d9591c592040b6302839bae645242c0bdd9c2963/geppetto-showcase/src/components/showcase/ShowcaseUtils.js#L74)to get component props information. 
- ShowcaseExamplesComponentMap is removed and replaced with more efficient changes made [here - line 121 & 126](https://github.com/MetaCell/geppetto-meta/blob/d9591c592040b6302839bae645242c0bdd9c2963/geppetto-showcase/src/components/showcase/ShowcaseUtils.js#L121) thanks to Afonso's review.
- VRCanvas is fully functional now (it wasn't previously).
- The problems with coloring for Canvas and node size in Graph components mentioned in my comment above still persist.

@afonsobspinto I am heading in the right direction with what you were thinking? Let me know!

**Comment by afonsobspinto** [comment]
Looking good to me thanks :+1: 
So you also fixed #133 ? That's great news.

What's missing beside the bugs?
Feel free to open a draft PR and add me as reviewer meanwhile

**Comment by Muhaddatha** [comment]
@afonsobspinto  sorry Afonso, that's not what I meant 😅. I meant that the showcase doesn't blow up when you click on the VR canvas tab. It previously did with my old refactoring. #133 still needs fixing. 

@enicolasgomez let me know if you approve and I can move onto the next step: using the CopyPlugin 🙂. Also left a list of bugs I noticed in the card above. I'm not sure where they are coming from, but will look into them more.

**Comment by afonsobspinto** [comment]
Fixed by https://github.com/MetaCell/geppetto-meta/pull/364
