### ISSUE TITLE
proxy instance color undefined for children should be retrieved from the parent instance

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-meta#306]
I noticed this on netpyne during selection, the behaviour is the following:

- proxyInstance contains the network instance with a color defined (lets say green).
- I select the instance network.E[11].
- this instance had color undefined but get a color due to the selected property set to true.
- when I unselect the instance gets a default color from geppetto rather than using the parent color.

Imo the responsability of retrieving the parent color should be handled by Geppetto since the proxy instances, from the application pov, are a list of flat instances and we are not exposing concept of hierarchy to the application.

Also, I noticed that the geppetto instances have methods for getColor and setColor but these are not working right now, not sure this is expected and these methods should be deprecated or we simply did not implement them yet, but they can be used to address the above in a quite simple way - ccing @filippomc to confirm if these methods should be removed or not.

Thx

**Comment by filippomc** [comment]
Yes getColor and setColor are deprecated https://github.com/MetaCell/geppetto-meta/blob/cd9fd81042c8253b2b31158b7a23f08d09d3fb51/geppetto.js/geppetto-core/src/capabilities/AVisualCapability.js#L64

**Comment by filippomc** [comment]
This issue can generalized as:
if we have instance A and A.B and both A and A.B are added as proxy instances, we want that if a property -any property- is defined in A but not in A.B, that property is inherited by A.B.
The current behaviour is that A.B inherits the properties from A unless it's added to the proxy instances, so the only way the application can make it work is to set the color explicitly in A and A.B proxy instances
