### ISSUE TITLE
Camera control actions throws an error "Reduce of empty array with no initial value" on the React-redux example app

### ISSUE THREAD

**Issue by paularah** [MetaCell/geppetto-meta#311]
A Series of camera control actions on the canvas throw up an error with the message `Reduce of empty array with no initial value`. I think this is related to #276 

### Steps to reproduce 
On the example app, add the 3D canvas, rotate and then pan in different directions. 

### Screenshots
https://user-images.githubusercontent.com/37967706/155701718-64224f94-c280-4d64-a718-b96650130026.mp4

**Comment by afonsobspinto** [comment]
As you mentioned, I believe this is the same issue as #276. Should be fixed with #277
