### ISSUE TITLE
Disable ongoing canvas re rendering on sidebar/window width resize

### ISSUE THREAD

**Issue by vidhya-metacell** [MetaCell/geppetto-meta#337]
So, whenever i expand/collapse the sidebar with a transition of very few seconds, the canvas re renders continuously. Same thing happens when i resize the window. Is there way or a property which could disable that? I am attaching a video to better explain what I mean.
This from project (salk)[https://github.com/MetaCell/salk-interactive-atlas]
To reproduce the same please checkout on branch feature/20-smoothen-sidebar
To run salk on your local system just install the npm packges and run "npm run start:dev" from applications/salk-portal folder

https://user-images.githubusercontent.com/71261494/157873469-9e4fdf3d-3fed-46cb-978d-bd1a9f8423e1.mov

**Comment by afonsobspinto** [comment]
I think this might relate with #328

**Comment by enicolasgomez** [comment]
We just re-checked on Salk and based on #328 it seems that it has been addressed already. There are some re-rendering taking place (e.g. window size change) but that's expected as the scene needs to be refreshed to the new size.
