### ISSUE TITLE
Add tooltip to canvas 

### ISSUE THREAD

**Issue by filippomc** [MetaCell/geppetto-meta#351]
Something like

```jsx
<Canvas ... tooltip={{
    text: (instanceId) => <p>{Instances.getInstance(instanceId).getName()}</p>,
    delay: 0, // 0 by default
}}/>
```

Implementation caveats:
- the tooltip is displayed on hover whenever the tooltip callback is specified
- the current onHover callback should still be available
- Be careful on state management: showing the tooltip should not cause a rerender of the canvas wrapper component

**Comment by zsinnema** [comment]
@filippomc is the instanceId the "proxy" instance id? Imo we should have access to the proxy instance too, because instances can be shared in different canvasses

**Comment by filippomc** [comment]
instances and "proxy" instances share the same id

**Comment by zsinnema** [comment]
my suggestion is to have also the proxy instance in the component;  so both instance and proxy instance

**Comment by filippomc** [comment]
Once the id is known the application is free to use the instance (from Instances global) or the proxy instance (from the redux store or component state) -or neither- for the callback component definition

**Comment by zsinnema** [comment]
but how does the component know what proxy instance it should use in case there are more proxy instances with the same instance id (e.g. on multiple canvasses)

**Comment by filippomc** [comment]
The proxy instances are well known in that place as it's a parameter od the Canvas

```jsx
<Canvas
        data={canvasData} //Proxy instances of this canvas
/>
```
