### ISSUE TITLE
canvas position reset all the times

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-meta#356]
https://user-images.githubusercontent.com/37704177/161992924-68851a21-236f-4cc7-b63f-c803e5ff8a5c.mp4

**Comment by afonsobspinto** [comment]
Potentially fixed with #330 

https://user-images.githubusercontent.com/19196034/162456500-7edcbaae-d85e-4d9a-89d4-30fbfb60ece3.mp4
