### ISSUE TITLE
Find a solution for apps using Geppetto showcase examples

### ISSUE THREAD

**Issue by Muhaddatha** [MetaCell/geppetto-meta#366]
With [#305](https://app.zenhub.com/workspaces/geppetto-meta-6047b13d88e7e70013d4589b/issues/metacell/geppetto-meta/305), all Geppetto showcase examples have been moved to the geppetto-showcase application. The examples are no longer in geppetto-ui.

For this reason, apps that previously relied on importing the examples directly form geppetto-ui cannot do this anymore.
For example, the redux-react example app tries to import the big image viewer example [here](https://github.com/MetaCell/geppetto-meta/blob/2f0a25116d82cdda55a081f6d6fbf926ee895231/examples/redux-react-app/src/app/componentMap.js#L2), but that file is no longer in geppetto-ui, so the apps crashes. I'm not sure if there are any other affected apps that import examples directly.

Three solutions come to my mind atm: 

1. Load geppetto-showcase into the project by using the [setup.sh](https://github.com/MetaCell/geppetto-meta/blob/development/examples/redux-react-app/setup.sh#L6) script and import examples from `@metacell/geppetto-showcase/src/examples/`.

2. Just use the plain components (not the example ones) and provide data to it wherever it is used. Correct me if I'm wrong, but I think this solution is not ideal because the example app will become slower with a ton of local data for the components and there may be some duplicate models for different components (once in the showcase & once wherever the component is being used).

3. Undo [#305](https://app.zenhub.com/workspaces/geppetto-meta-6047b13d88e7e70013d4589b/issues/metacell/geppetto-meta/305) potentially.

**Comment by afonsobspinto** [comment]
Nice catch @Muhaddatha . I didn't know the redux-react-app was using geppetto-showcase examples.

I'm voting for your proposal number 2. The downsides you mentioned are true, but if we plan it right, within the scope of #256 , we might find something that doesn''t end up with duplicate examples. We want those 2 applications to serve different purposes so I think having different examples is actually part of the plan.
