### ISSUE TITLE
Remove log from trackball controls

### ISSUE THREAD

**Issue by afonsobspinto** [MetaCell/geppetto-meta#377]
console.log() probably added to debug. Imo should be removed:
https://github.com/MetaCell/geppetto-meta/blob/master/geppetto.js/geppetto-ui/src/3d-canvas/threeDEngine/TrackballControls.js#L319

**Comment by Wilson-Ramos** [comment]
Hello, I would like to work on this issue.

**Comment by afonsobspinto** [comment]
Thanks. Looking forward for your PR :rocket:
