### ISSUE TITLE
Dicomviewer Broken Locally

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/geppetto-meta#394]
**The Issue Description** 

I'm facing a weird issue with the geppetto-meta showcase. I'm running the showcase locally, and I'm not able to see the DicomViewer working. The error is below, happens with components using 'ami.js' library. The issue seems to be a mismatch between code transpile as ES6 and ES5, but it's weird that only happens locally on my machine and not on [geppetto.metacell.us](http://geppetto.metacell.us/) deployment. Any insights would be appreciated.

**Steps to Reproduce:**

- Checkout development branch of geppetto-meta
- Run ./setup.sh from geppetto-meta/geppetto-showcase
- Run 'yarn start'
- Open up DicomViewer on show-case when ready.

**Error** 
```
react-dom.development.js:11340 Uncaught TypeError: Class constructor EventDispatcher cannot be invoked without 'new'
    at new _class (ami.js:28739:1)
    at Object.initRenderer3D (DicomViewerUtils.js:257:26)
    at init (DicomViewer.js:239:26)
    at DicomViewer.loadModel (DicomViewer.js:249:7)
    at DicomViewer.componentDidMount (DicomViewer.js:589:10)
    at commitLifeCycles (react-dom.development.js:20663:1)
```

**Comment by afonsobspinto** [comment]
Thanks for raising this issue with such a clear path to reproduce it. :+1: 
I tried it myself and it seems that the problem is already fixed. 
Feel free to reopen the issue if you are still suffering from this problem with latest development
