### ISSUE TITLE
Fix dependencies (both remove and fix versions)

### ISSUE THREAD

**Issue by enicolasgomez** [MetaCell/geppetto-meta#407]
Branch already there feature/fix_dependencies

Related to #313 and #312

**Comment by enicolasgomez** [comment]
@filippomc check about backbone, bootstrap, codemirror? hardly probable needed

**Comment by enicolasgomez** [comment]
Check for peerDependencies

**Comment by enicolasgomez** [comment]
Check dependencies for #312

https://github.com/MetaCell/geppetto-meta/pull/312/files#diff-eddf23bc22304a0773bf7a37c6fdde524ca4fb21795b28994dd6ed67bb5581ea

**Comment by enicolasgomez** [comment]
Upgrade NodeJS style class in geppetto-core

**Comment by enicolasgomez** [comment]
Check aframe in relation with VR functionality

**Comment by enicolasgomez** [comment]
Replace UI fontawesome icons with material UI ones to remove the dependencies

**Comment by enicolasgomez** [comment]
Check "d3": "4.0.0" - which components breaks latest

**Comment by afonsobspinto** [comment]
Sharing here my slack messages for tracking purposes:
![image](https://user-images.githubusercontent.com/19196034/198627900-af0d648c-baf9-4cc9-993d-97664a2f3c56.png)

**Comment by enicolasgomez** [comment]
@afonsobspinto ok, I will upgrade geppetto to 534 and see if that brakes anything. If that's not the case will get a new release going.

**Comment by enicolasgomez** [comment]
@Anto8819 as you reported, I could verify that there are some dependencies issues with the react-redux-app installation, let's do the following on package.json

- Modify package.json file to use dynamic binding for geppetto-meta (copy from geppetto-showcase):
https://github.com/MetaCell/geppetto-meta/blob/master/geppetto-showcase/package.json#L59
- Build latest geppetto-meta and publish: yarn build:src && yalc push build
- Check for unnecesary dependencies on react-deux app and remove
- Fix necessary dependencies to match geppetto-meta 's version

**Comment by Anto8819** [comment]
Resolved: Dependencies has been fixed on #451
