### ISSUE TITLE
Remove debug message from geppetto middleware

### ISSUE THREAD

**Issue by afonsobspinto** [MetaCell/geppetto-meta#498]
https://github.com/MetaCell/geppetto-meta/blob/development/geppetto.js/geppetto-client/src/common/middleware/geppettoMiddleware.js#L24

**Comment by AhmedMustafa2201** [comment]
@afonsobspinto i think it's closed, right?

**Comment by afonsobspinto** [comment]
Soon to be closed yes. Thanks for your interest in it anyway :+1:
