### ISSUE TITLE
Add Slice Plane Functionality to Canvas

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/geppetto-meta#534]
Previously the Geppetto Canvas used to support a feature called 'Slice Plane'. It allowed a plane geometry to be drawn on the Canvas, when requested from an external UI or command. In our case, we were using it from the SliceViewer Component. This task is to add back a camera control that allows a Slice Plane to be drawn on the Canvas

**Comment by afonsobspinto** [comment]
I might be missing some context but I believe that it's still possible to add any ThreeDObject to the canvas using the [threeDObjects prop](https://github.com/MetaCell/geppetto-meta/blob/master/geppetto.js/geppetto-ui/src/3d-canvas/Canvas.js#L650)

**Comment by jrmartin** [comment]
@afonsobspinto You are right, thanks!
