### ISSUE TITLE
BigImageViewer on showcase shows pixelated image at bottom of zoom

### ISSUE THREAD

**Issue by slarson** [MetaCell/geppetto-meta#61]
<img width="824" alt="Screen Shot 2021-05-05 at 10 45 44 AM" src="https://user-images.githubusercontent.com/1037756/117162000-65380c80-ad90-11eb-8611-28517763985e.png">

When I zoom into the image in the showcase, I see the screenshot.  Having worked on the dataset myself, I think it is possible that the viewer is having one of two issues:

1. Either not loading the bottom most images from the image pyramid -- I think there may actually be more detailed images in the pyramid that it just is failing to load - OR -
2. Allowing the user to zoom in too far into the images at the bottom of the pyramid

Either way, the experience should be that the user never sees something like the screen shot; if there are no more detailed images to load it should prevent the user from zooming in beyond a "good looking" resolution at the bottom.

**Comment by afonsobspinto** [comment]
Image was replaced by a new example
