### ISSUE TITLE
TreeViewer not working with React 17.0.x

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/geppetto-meta#65]
react-sortable-tree doesn't work with 17.x.x React version: https://github.com/frontend-collective/react-sortable-tree/issues/840

**Comment by nosferatu500** [comment]
Hi! I made fork of this library and fix issue with React 17

```
yarn add @nosferatu500/react-sortable-tree
```

https://github.com/nosferatu500/react-sortable-tree

**Comment by lrebscher** [comment]
thx @nosferatu500 for reaching out!
