### ISSUE TITLE
Improvement of camera changes through interaction

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/geppetto-meta#75]
The task can be divided in 2 parts:

- make possible from the props given to the Canvas component to tweak the default incrementRotation and incrementZoom, so that each application can decide what the factor handled by the camera controls should be. These are defined [here](https://github.com/MetaCell/geppetto-meta/blob/cd9fd81042c8253b2b31158b7a23f08d09d3fb51/geppetto.js/geppetto-ui/src/3d-canvas/Canvas.js#L137) and [here](https://github.com/MetaCell/geppetto-meta/blob/cd9fd81042c8253b2b31158b7a23f08d09d3fb51/geppetto.js/geppetto-ui/src/3d-canvas/Canvas.js#L142), default props and propTypes are defined at the bottom of Canvas component.

- This is like the above, with the difference that we should be able to tweak also the rotation and zoom triggered by the mouse and handled by the TrackballControls. We should be able to define these 2 factors and then these should be passed down the line to the TrackballControls class instatiation so that these values will replace the default used right now.

**Comment by afonsobspinto** [comment]
I wouldn't say that the current canvas zoom using camera controls needs a tweak and if it does I would say it should be a tweak to make it smaller not greater.
Leaving the final word to you @enicolasgomez

**Comment by enicolasgomez** [comment]
Since we moved to an  "on demand rendering" this won't be trivial to implement, I see this similar to the camera spin button in which requestRenderFrame will be triggered by a setTimeOut call with the extra complecity of the rotation angle. I don't think it worth the effort right now.

**Comment by afonsobspinto** [comment]
Reopened since we want to be able to also tweak the amount of movement using the trackball controls (not only the camera controls).

**Comment by afonsobspinto** [comment]
fixed by https://github.com/MetaCell/geppetto-meta/pull/316
