### ISSUE TITLE
Typescript compiler - out of memory in Docker build

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/geppetto-meta#82]
Step 21/25 : RUN npm run build
 ---> Running in 8b31852e12bf

> geppetto-website@0.0.1 build /app/geppetto-showcase
> webpack --mode production

ℹ ｢atl｣: Using typescript@2.9.2 from typescript
ℹ ｢atl｣: Using tsconfig.json from /app/geppetto-showcase/tsconfig.json

<--- Last few GCs --->

[18:0x55f8832c0360]   217195 ms: Mark-sweep 2037.8 (2057.3) -> 2035.5 (2058.5) MB, 1070.9 / 0.0 ms  (average mu = 0.164, current mu = 0.029) allocation failure scavenge might not succeed
[18:0x55f8832c0360]   218619 ms: Mark-sweep 2039.5 (2066.5) -> 2037.2 (2068.3) MB, 1204.4 / 0.0 ms  (average mu = 0.159, current mu = 0.154) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

**Comment by filippomc** [comment]
One quick fix can be to add the following to the [package.json script](https://github.com/MetaCell/geppetto-meta/blob/e469729d10d05c35e889529aa7728e7af2fede06/geppetto-showcase/package.json#L10):

`--env NODE_OPTIONS='--max-old-space-size=12048'`

**Comment by filippomc** [comment]
Possible ways to reduce the memory requirement:

- Update typescript and use babel with ts-loader in place of the less widely used and ad-hoc awesome-typescript-loader
- Use copy-webpack-plugin to include resources in the showcase rathedr than import (example: https://github.com/MetaCell/geppetto-meta/blob/e469729d10d05c35e889529aa7728e7af2fede06/geppetto.js/geppetto-ui/src/3d-canvas/showcase/examples/AuditoryCortexExample.js#L76)
- Use precompiled Geppetto form npm will also reduce a lot the webpack requirements
